version: '3.8'

services:
  app:
    image: forum-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3307/forum?allowPublicKeyRetrieval=true&useSSL=false
    depends_on:
      - db
    networks:
      - forum-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: forum
      MYSQL_USER: your_db_user
      MYSQL_PASSWORD: your_db_password
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - forum-network

volumes:
  db-data:

networks:
  forum-network:
