spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/forum?allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USER}  # Certifique-se de que as variáveis de ambiente estejam configuradas
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none  # Evita que o Hibernate tente criar ou modificar o esquema automaticamente
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  flyway.locations.filesystem: db/migration
  jwt:
    secret: ${JWT_SECRET}