spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/forum?useSSL=false
    username: ${DB_USER}  # Certifique-se de que as variáveis de ambiente estejam configuradas
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none  # Evita que o Hibernate tente criar ou modificar o esquema automaticamente
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: true  # Habilita o Flyway
    locations: classpath:db/migration  # Local padrão das migrations Flyway (pode ser alterado se necessário)
    baseline-on-migrate: true  # Isso garante que o Flyway reconheça o estado atual do banco se ele já tiver dados
    placeholder-replacement: true  # Para garantir que os placeholders sejam substituídos
  jwt:
    secret: ${JWT_SECRET}