spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/forum
    username: root  # Certifique-se de que as variáveis de ambiente estejam configuradas
    password: root
  jpa:
    hibernate:
      ddl-auto: none  # Evita que o Hibernate tente criar ou modificar o esquema automaticamente
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 8e2eae2efd4b67
    password: 9301c159d1fec6
    properties:
      mail:
        transport:
          protocol: smtp
        debug: true
        smtp:
          auth: true
          starttls:
              enable: true
  flyway.locations.filesystem: db/migration
  jwt:
    secret: secret